import os
import sys
import json
import re
import time
from pptx import Presentation
from pptx.util import Inches, Pt
from google import genai
from dotenv import load_dotenv

# Load API Key
load_dotenv()
API_KEY = os.getenv("GEMINI_API_KEY")

class PPTGenerator:
    def __init__(self, models_to_try=["gemini-2.5-flash", "gemini-2.0-flash", "gemini-1.5-flash", "gemini-pro"]):
        if not API_KEY:
            print("Error: GEMINI_API_KEY not found in .env file.")
            sys.exit(1)
            
        self.client = genai.Client(api_key=API_KEY)
        self.model_id = None
        
        for model in models_to_try:
            try:
                # Test connectivity
                self.client.models.generate_content(model=model, contents="test")
                self.model_id = model
                print(f"✓ Using model: {model}")
                break
            except Exception:
                continue
        
        if not self.model_id:
            print("Error: Could not initialize any Gemini model. Check your API key and Quota.")
            sys.exit(1)

    def generate_content(self, topic, num_slides):
        prompt = f"""
        Generate a presentation on the topic: '{topic}' with exactly {num_slides} slides.
        The output must be in STRICT JSON format as a list of slide objects.
        Each slide object must have:
        - "title": Title of the slide
        - "content": A list of bullet points (3-5 points)
        - "image_prompt": A descriptive prompt for an image related to the slide content
        - "video_link": A relevant YouTube search link for the slide topic

        Return ONLY the JSON. No markdown formatting markers.
        """
        
        try:
            response = self.client.models.generate_content(
                model=self.model_id,
                contents=prompt
            )
            text = response.text
            
            # Clean up JSON if Gemini wraps it in markdown blocks
            if "```json" in text:
                text = re.search(r"```json\n(.*?)\n```", text, re.DOTALL).group(1)
            elif "```" in text:
                text = re.search(r"```\n(.*?)\n```", text, re.DOTALL).group(1)
                
            return json.loads(text)
        except Exception as e:
            if "429" in str(e) or "ResourceExhausted" in str(e):
                print("Error: Gemini Rate Limit (Quota) exceeded. Please wait 60 seconds and try again.")
            else:
                print(f"Error during content generation: {e}")
            return None

    def create_ppt(self, topic, slides_content, output_file="presentation.pptx"):
        prs = Presentation()
        
        # Title Slide
        title_slide_layout = prs.slide_layouts[0]
        slide = prs.slides.add_slide(title_slide_layout)
        title = slide.shapes.title
        subtitle = slide.placeholders[1]
        title.text = topic
        subtitle.text = "Generated by Gemini AI"

        for slide_data in slides_content:
            bullet_slide_layout = prs.slide_layouts[1]
            slide = prs.slides.add_slide(bullet_slide_layout)
            
            # Set Title
            title_shape = slide.shapes.title
            title_shape.text = slide_data.get("title", "Untitled Slide")
            
            # Set Bullet Points
            content_shape = slide.placeholders[1]
            tf = content_shape.text_frame
            tf.text = "" # Clear default
            
            points = slide_data.get("content", [])
            for point in points:
                p = tf.add_paragraph()
                p.text = point
                p.level = 0
            
            # Add Links at the bottom
            video_link = slide_data.get("video_link", "")
            if video_link:
                footer_para = tf.add_paragraph()
                footer_para.text = f"\nVideo Resource: {video_link}"
                footer_para.font.size = Pt(12)
                footer_para.font.italic = True

        prs.save(output_file)
        print(f"✓ Presentation saved to {output_file}")

def main():
    import sys
    if len(sys.argv) < 3:
        print("Usage: python ppt_generator.py \"Topic Name\" <num_slides>")
        return

    topic = sys.argv[1]
    try:
        num_slides = int(sys.argv[2])
    except ValueError:
        print("Error: Number of slides must be an integer.")
        return

    gen = PPTGenerator()
    print(f"Generating content for '{topic}' with {num_slides} slides...")
    
    content = gen.generate_content(topic, num_slides)
    if content:
        print("Content generated successfully. Creating PPTX...")
        output_name = f"{topic.replace(' ', '_')}_presentation.pptx"
        gen.create_ppt(topic, content, output_name)
    else:
        print("Failed to generate content.")

if __name__ == "__main__":
    main()
